############################
#     VoidWarp - Config    #
############################

world:
  # mode: The warp mode to use when the player is in the region (COMMAND/LOCATION/SPAWN/WARP)
  mode: SPAWN
  # yMin: The Y coordinate at the bottom of the range (Leave empty to have no minimum)
  yMin: -1000
  # yMax: The Y coordinate at the top of the range (Leave empty to have no maximum)
  yMax: 0
  # message: The message that is displayed in chat when you are teleported
  message: "&#b7faa2Teleported to &#66b04f%location%"

world_warp_example:
  mode: WARP
  yMin: -1000
  yMax: 0
  message: "&#b7faa2Teleported to &#66b04f%location%"
  warps: []
  whitelist: false